#!/bin/bash 

PARTIALS=$(ls -1)

JADE="./ractive-partials.pug"
LS="./ractive-partials.ls"

echo "// Generated by $(basename $0)" > $JADE
echo "# Generated by $(basename $0)" > $LS

for i in $PARTIALS
do 
  if [[ -d $i ]]; then 
    echo "partial found: $i"
    touch "$i/index.ls"
    touch "$i/widget.pug"
    touch "$i/widget.css"
    
    echo "require './$i'" >> $LS
    echo "include ./$i/widget.pug" >> $JADE
    
  else 
    echo "these are not partials: $i"
  fi
  
done