#!/bin/bash

# include libs
CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$CURR_DIR/../.."
TOOLS_DIR="$ROOT_DIR/tools"
PROJECT_NAME="$(basename $CURR_DIR)"
. "${TOOLS_DIR}/lib/tmux-launch"

# exports
export PATH="${TOOLS_DIR}/aktos-espruino-tools:${PATH}"
export NODE_PATH="${ROOT_DIR}/src/lib:$NODE_PATH"

cd "$ROOT_DIR"

# run commands
start-tmux-session 0
run-in-tmux "gulp --project $PROJECT_NAME"
run-in-tmux "cd $CURR_DIR/webserver" 'lsc server.ls'
run-in-tmux 'xdg-open . 2> /dev/null' 'atom .'

# Show in terminal
attach-tmux-session 0
