// Generated by LiveScript 1.4.0
(function(){
  var hapi, httpProxy, server;
  hapi = require("hapi");
  httpProxy = require('http-proxy');
  server = new hapi.Server();
  server.connection({
    port: 5000,
    routes: {
      cors: true
    }
  });
  server.register(require('h2o2'), function(){});
  server.register(require('inert'), function(){});
  server.route({
    method: '*',
    path: '/kds/{f*}',
    handler: {
      proxy: {
        mapUri: function(request, callback){
          var resourceUri, url;
          resourceUri = request.url.path.replace('/kds/', '/');
          url = "http://192.168.1.15/DemeterKds/api/rfm/ScoresVersion?rawMaterialCode=19&VersionNumber=635973759505058264";
          console.log('url: ', url);
          return callback(null, url);
        },
        passThrough: true,
        xforward: true
      }
    }
  });
  server.route({
    path: "/",
    method: "GET",
    handler: {
      file: "./public/index.html"
    }
  });
  server.route({
    path: "/app.ls",
    method: "GET",
    handler: {
      file: "./public/app.ls"
    }
  });
  server.route({
    path: "/scripts/{f*}",
    method: "GET",
    handler: {
      directory: {
        path: "./public/scripts"
      }
    }
  });
  server.start(function(){
    console.log("Server started at: ", server.info.uri);
  });
}).call(this);
