# Do not edit this file manually! 
require! './ace-editor'
require! './ack-button'
require! './ddoc-editor'
require! './interactive-table'
require! './login'
require! './menu'
require! './order-table'
module.exports = { ace-editor, ack-button, ddoc-editor, interactive-table, login, menu, order-table }
