# Do not edit this file manually! 
require! './ace-editor'
require! './ddoc-editor'
require! './interactive-table'
require! './login'
module.exports = { ace-editor, ddoc-editor, interactive-table, login }
