# Do not edit this file manually! 
require! './inspina-menu'
require! './inspina-theme'
require! './inspina-header'
require! './inspina-content'
require! './inspina-footer'
module.exports = { inspina-menu,inspina-header,inspina-content,inspina-footer }
