#!/bin/bash

# include libs
CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$CURR_DIR"
. ./lib/tmux-launch

export NODE_PATH="${CURR_DIR}/../src/lib:$NODE_PATH"

# run commands
cd "$CURR_DIR/.."

start-tmux-session 0
run-in-tmux 'gulp'
run-in-tmux 'cd ./src/server/demeter/webserver' 'lsc server.ls'
run-in-tmux 'xdg-open . 2> /dev/null' 'atom .'

# Show in terminal
attach-tmux-session 0
