#!/bin/bash

# include libs 
CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$CURR_DIR"
. ./tmux-launch

# run commands
cd "$CURR_DIR/.."

start-tmux-session 0
run-in-tmux 'gulp'
run-in-tmux 'cd ./src/server' 'lsc server.ls'
run-in-tmux 'xdg-open .' 'atom .'

# Show in terminal
attach-tmux-session 0
