#!/bin/bash
safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; _sdir=$(dirname "$(readlink -f "$0")"); }; safe_source
DIR="$_dir"

[[ -f "$_sdir/node-path.sh" ]] && source "$_sdir/node-path.sh"

watch=
if [[ "$1" = "-w" ]]; then
    echo "Watch mode enabled."
    watch=true
    shift
fi

filename=$1

if [[ ! -f $filename ]]; then
    echo "First argument should be a file to run."
    exit 255
fi

lsFile="$filename"
shift
set-pane-title () {
    if [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; then
        #tmux select-pane -T $1                 # right corner
        #tmux set pane-border-status bottom     # extra line 
        tmux rename-window $1
    fi

}
set-pane-title ${lsFile%.ls}

if [[ -z $watch ]]; then
    lsc $lsFile "$@"
else

    LTIME=
    CMD_PID=

    cleanup(){
        [[ -n $CMD_PID ]] && kill $CMD_PID
    }
    trap cleanup EXIT

    while :; do
       ATIME=`stat -c %Z "$lsFile"`
       if [[ "$ATIME" != "$LTIME" ]]; then
            if [[ -n $CMD_PID ]]; then
                echo "---------------------------------------"
                echo "|             Restarting...           |"
                echo "---------------------------------------"
                kill $CMD_PID
            fi
            lsc $lsFile "$@" &
            CMD_PID=$!
            LTIME=$ATIME
       fi
       sleep 2
    done
fi
