#!/bin/bash

# include libs
CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$CURR_DIR"
. ./lib/tmux-launch

# run commands
cd "$CURR_DIR/.."

start-tmux-session 0
run-in-tmux 'cd ./tools' './update-production.sh'
run-in-tmux 'cd ./src/server/webserver' 'lsc server.ls'

# Show in terminal
attach-tmux-session 0
